name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/~/CounterPro"

    - name: Retrieve current version from readme.md
      id: get_version
      run: |
        version=$(grep -Po 'Current Version: `\K[0-9]+\.[0-9]+\.[0-9]+' readme.md)
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: Create config file on VPS for Bot
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo 'module.exports = {
                  token: "${{ secrets.BOT_TOKEN }}",
                  applicationClientId: "${{ secrets.CLIENT_ID }}",
                  databaseHost: "${{ secrets.DB_HOST }}",
                  databaseUser: "${{ secrets.DB_USER }}",
                  databasePassword: "${{ secrets.DB_PASSWORD }}",
                  databaseName: "${{ secrets.DB_NAME }}",
                  databasePort: 3306,
                  supportServerInvite: "https://discord.gg/u6w8HuzzgX",
                  currentVersion: "${{ env.VERSION }}"
              }' > /~/CounterPro/application/config.js

    - name: Create .env file on VPS for Laravel
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo 'APP_NAME="CounterPro"
          APP_ENV=local
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=true
          APP_URL=http://localhost
          LOG_CHANNEL=stack
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          CACHE_DRIVER=file
          SESSION_DRIVER=file
          QUEUE_CONNECTION=sync
          ' > /~/CounterPro/website/.env

    - name: Restart Docker containers
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /~/CounterPro/
          docker-compose down
          docker-compose up -d --build
          docker image prune -af
