name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/~/CounterPro"

    - name: Create config file on VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo 'module.exports = {
                  token: "${{ secrets.BOT_TOKEN }}",
                  applicationClientId: "${{ secrets.CLIENT_ID }}",
                  databaseHost: "${{ secrets.DB_HOST }}",
                  databaseUser: "${{ secrets.DB_USER }}",
                  databasePassword: "${{ secrets.DB_PASSWORD }}",
                  databaseName: "${{ secrets.DB_NAME }}",
                  databasePort: 3306,
                  supportChannel: 1273048334939984024
              }' > /~/CounterPro/config.js

    - name: Restart Docker container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /~/CounterPro
          docker-compose down
          docker-compose up -d --build
